services:
  mir-bot:
    image: miran2025/mir-cat-tg-bot:latest
    container_name: mir-cat-tg-bot
    command: [ "uv", "run", "-m", "src.main" ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres-bot-db
    networks:
      - local

  postgres-bot-db:
    image: postgres:17.3-alpine
    container_name: postgres-bot-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    restart: unless-stopped

networks:
  local:
    driver: bridge

volumes:
  postgres_data:
